### ISSUE TITLE
loss of precision

### ISSUE THREAD

**Issue by pjyong** [diegolopezgrisanti/measurement-unit-converter#1]
Hello, thanks for your cool library.

I found one problem of loss of precision, can you make this line code of 'value * conversionRate' flexsible?

So I can use 'multipliedBy' of BigNumber library to finish it.

**Comment by diegolopezgrisanti** [comment]
Hello June Peng!
Thanks for your comment.

I have fixed the loss of precision problem. In the latest version of measurement-unit-converter you will see this new functionality.
I hope it is useful to you. I'm to help you.

Nice to meet you. See you later!
